import { Component } from '@angular/core';
import { Recipe } from './recipe.model'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  recipes: Recipe[] = [
    new Recipe('Simple Omelet', ['Fresh Eggs x 1', 'Coarse Rock Salt x 1'],
      ['Superb Dish: Soft & Fluffy Omelet - Recovers 100 HP & Cures KO', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      ''),
    new Recipe('', [''],
      ['Superb Dish: ', 'Regular Dish: ', 'Peculiar Dish: ', 'Unique Dish: '],
      ['Rean: ', 'Alisa: ', 'Elliot: ', 'Machias: ', 'Emma: ', 'Jusis: ', 'Fie: ', 'Gaius: ', 'Crow: ', 'Millium: '],
      '')
  ];
}
